# go to sleep after one hour (1*60*60*1000ms)

CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=7200000

CONFIG_ZMK_SLEEP=y

#CONFIG_ZMK_HID_CONSUMER_REPORT_USAGES_BASIC=y

#The maximum brightness percentage of RGB，Reducing this value can lower the temperature of the rectifier components.(RGB的最大百分比亮度，降低可以减少发热）



# MOUSE
CONFIG_ZMK_MOUSE=y

CONFIG_BT_CTLR_TX_PWR_PLUS_8=y
CONFIG_ZMK_HID_REPORT_TYPE_NKRO=n

#缩小数值减少延迟但对轴体品质要求会更高 Reducing the value will decrease the latency, but it will also place higher demands on the switching quality. If you are confident about the quality of the switch used on the keyboard, you can try smaller values, such as 1ms - 3ms.
#soft off
CONFIG_ZMK_PM_SOFT_OFF=y



# Required for DYA runtime encoder bindings on ZMK/Zephyr 4.1
CONFIG_ZMK_BEHAVIOR_LOCAL_IDS_IN_BINDINGS=y

# 关闭触摸功能
CONFIG_PROSPECTOR_TOUCH_ENABLED=n

# 关闭光线传感器（使用固定亮度）
CONFIG_PROSPECTOR_USE_AMBIENT_LIGHT_SENSOR=n
# 设置固定亮度值（0-100，视你的喜好调整）
CONFIG_PROSPECTOR_FIXED_BRIGHTNESS=80
